

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.91.133/sell?characterEncoding=utf-8&useSSL=false
  jackson:
      default-property-inclusion: non_null
  jpa:
    show-sql: true


server:
  context-path: /sell

wechat:
  mpAppId:wx17cf04d36064b568
  mpAppSecret:d54aa38de5a38f5e251ead307a58f909




